### ISSUE TITLE
so文件链接失败。编译最新2.3.0也是如此

### ISSUE THREAD

**Issue by huangjingqiang** [fzkf9225/shadow-plugin-master#2]

**Comment by EmptyPages** [comment]
日志呢？？？

**Comment by huangjingqiang** [comment]
尝试自己生成一个静态so是可以正常加载的；使用公司业务so不行。猜想使用动态库是不能够正常使用的。


Process: com.casic.titan.shadow:plugin, PID: 3230
                                                                                                    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/user/0/com.casic.titan.shadow/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/fbe80e42945f0e85220c135e91a5841b/plugin-debug.zip/plugin-user-plugin-debug.apk!/lib/arm64-v8a/libjiagu_sdk_OSETSDKProtected.so"

**Comment by EmptyPages** [comment]
如果我没记错的话，我的demo里没加这个so，还有就是如果你改了自己那边的项目的话，记得改相关包名什么的，你上面包名还是我demo的
